-- Create small disposable tables used by the role checks.
USE ROLE SYSADMIN;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;

CREATE OR REPLACE TRANSIENT TABLE INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK (
  ID NUMBER(38, 0),
  NOTE VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE INDUSTRIAL_SERVICE_DB.STAGING.ACCESS_CHECK (
  ID NUMBER(38, 0),
  NOTE VARCHAR
);

CREATE OR REPLACE TRANSIENT TABLE INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK (
  ID NUMBER(38, 0),
  NOTE VARCHAR
);

INSERT INTO INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK VALUES (1, 'raw');
INSERT INTO INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK VALUES (1, 'analytics');
