-- Expected to succeed when ISP_LOADER is granted to the current user.
USE ROLE ISP_LOADER;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;

INSERT INTO INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK VALUES (2, 'loader');
SELECT COUNT(*) AS RAW_ROW_COUNT
FROM INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK;

SELECT COUNT(*) AS PIPELINE_RUN_COUNT
FROM INDUSTRIAL_SERVICE_DB.OPERATIONS.PIPELINE_RUNS;
