-- Expected to succeed when ISP_TRANSFORMER is granted to the current user.
USE ROLE ISP_TRANSFORMER;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;

SELECT COUNT(*) AS RAW_ROW_COUNT
FROM INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK;

INSERT INTO INDUSTRIAL_SERVICE_DB.STAGING.ACCESS_CHECK VALUES (1, 'transformer');
SELECT COUNT(*) AS STAGING_ROW_COUNT
FROM INDUSTRIAL_SERVICE_DB.STAGING.ACCESS_CHECK;
