-- Expected to succeed when ISP_ANALYST is granted to the current user.
USE ROLE ISP_ANALYST;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;

SELECT COUNT(*) AS ANALYTICS_ROW_COUNT
FROM INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK;
