-- Run each statement separately. Every statement below should fail.

USE ROLE ISP_LOADER;
SELECT * FROM INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK;

USE ROLE ISP_TRANSFORMER;
INSERT INTO INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK VALUES (3, 'must fail');

USE ROLE ISP_ANALYST;
INSERT INTO INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK VALUES (2, 'must fail');

USE ROLE ISP_ANALYST;
SELECT * FROM INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK;
