-- Remove the disposable access-check tables.
USE ROLE SYSADMIN;

DROP TABLE IF EXISTS INDUSTRIAL_SERVICE_DB.RAW.ACCESS_CHECK;
DROP TABLE IF EXISTS INDUSTRIAL_SERVICE_DB.STAGING.ACCESS_CHECK;
DROP TABLE IF EXISTS INDUSTRIAL_SERVICE_DB.ANALYTICS.ACCESS_CHECK;
