-- Create reusable operational views without changing business data.
USE ROLE SYSADMIN;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA OPERATIONS;

CREATE OR REPLACE VIEW V_LATEST_PIPELINE_RUN AS
SELECT
  RUN_ID,
  SOURCE_NAME,
  STARTED_AT,
  FINISHED_AT,
  STATUS,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  ERROR_MESSAGE,
  CREATED_AT
FROM PIPELINE_RUNS
QUALIFY ROW_NUMBER() OVER (ORDER BY STARTED_AT DESC, CREATED_AT DESC) = 1;

CREATE OR REPLACE VIEW V_LATEST_INGESTION_RESULTS AS
SELECT
  RESULT_ID,
  RUN_ID,
  DATASET_NAME,
  SOURCE_FILE_NAME,
  LOAD_BATCH_ID,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  STATUS,
  CREATED_AT
FROM INGESTION_RESULTS
QUALIFY ROW_NUMBER() OVER (
  PARTITION BY DATASET_NAME
  ORDER BY CREATED_AT DESC, RESULT_ID DESC
) = 1;

GRANT SELECT ON VIEW V_LATEST_PIPELINE_RUN TO ROLE ISP_ADMIN;
GRANT SELECT ON VIEW V_LATEST_INGESTION_RESULTS TO ROLE ISP_ADMIN;
