USE ROLE ISP_ADMIN;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA OPERATIONS;

SELECT * FROM V_LATEST_PIPELINE_RUN;

SELECT
  DATASET_NAME,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  STATUS,
  CREATED_AT
FROM V_LATEST_INGESTION_RESULTS
ORDER BY DATASET_NAME;
