USE ROLE ISP_ADMIN;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SELECT 'RAW.ERP_CUSTOMERS' AS RELATION_NAME, COUNT(*) AS ROW_COUNT FROM RAW.ERP_CUSTOMERS
UNION ALL SELECT 'RAW.ERP_SITES', COUNT(*) FROM RAW.ERP_SITES
UNION ALL SELECT 'RAW.ERP_ASSETS', COUNT(*) FROM RAW.ERP_ASSETS
UNION ALL SELECT 'RAW.CRM_SERVICE_CONTRACTS', COUNT(*) FROM RAW.CRM_SERVICE_CONTRACTS
UNION ALL SELECT 'RAW.CRM_CUSTOMER_CASES', COUNT(*) FROM RAW.CRM_CUSTOMER_CASES
UNION ALL SELECT 'RAW.CRM_CASE_STATUS_HISTORY', COUNT(*) FROM RAW.CRM_CASE_STATUS_HISTORY
UNION ALL SELECT 'RAW.ERP_TECHNICIANS', COUNT(*) FROM RAW.ERP_TECHNICIANS
UNION ALL SELECT 'RAW.ERP_SERVICE_ORDERS', COUNT(*) FROM RAW.ERP_SERVICE_ORDERS
UNION ALL SELECT 'RAW.ERP_PARTS', COUNT(*) FROM RAW.ERP_PARTS
UNION ALL SELECT 'RAW.ERP_SERVICE_ORDER_PARTS', COUNT(*) FROM RAW.ERP_SERVICE_ORDER_PARTS
UNION ALL SELECT 'RAW.ERP_SERVICE_COSTS', COUNT(*) FROM RAW.ERP_SERVICE_COSTS
UNION ALL SELECT 'RAW.MONITORING_EQUIPMENT_ALERTS', COUNT(*) FROM RAW.MONITORING_EQUIPMENT_ALERTS
UNION ALL SELECT 'RAW.FIELD_SERVICE_TECHNICIAN_NOTES', COUNT(*) FROM RAW.FIELD_SERVICE_TECHNICIAN_NOTES
UNION ALL SELECT 'ANALYTICS.MART_ASSET_RELIABILITY', COUNT(*) FROM ANALYTICS.MART_ASSET_RELIABILITY
UNION ALL SELECT 'ANALYTICS.MART_CUSTOMER_PERFORMANCE', COUNT(*) FROM ANALYTICS.MART_CUSTOMER_PERFORMANCE
UNION ALL SELECT 'ANALYTICS.MART_KPI_SUMMARY', COUNT(*) FROM ANALYTICS.MART_KPI_SUMMARY
UNION ALL SELECT 'ANALYTICS.MART_TECHNICIAN_NOTE_ENRICHMENT', COUNT(*) FROM ANALYTICS.MART_TECHNICIAN_NOTE_ENRICHMENT
ORDER BY RELATION_NAME;
