-- ACCOUNTADMIN is used only for explicit account-level cost review in Snowsight.
USE ROLE ACCOUNTADMIN;

SHOW WAREHOUSES LIKE 'INDUSTRIAL_SERVICE_WH';
SHOW RESOURCE MONITORS LIKE 'INDUSTRIAL_SERVICE_MONITOR';

SELECT
  WAREHOUSE_NAME,
  SUM(CREDITS_USED_COMPUTE) AS COMPUTE_CREDITS,
  SUM(CREDITS_USED_CLOUD_SERVICES) AS CLOUD_SERVICE_CREDITS,
  SUM(CREDITS_USED) AS TOTAL_CREDITS
FROM SNOWFLAKE.ACCOUNT_USAGE.WAREHOUSE_METERING_HISTORY
WHERE WAREHOUSE_NAME = 'INDUSTRIAL_SERVICE_WH'
  AND START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
GROUP BY WAREHOUSE_NAME;
