-- Review only a bounded time range because ACCOUNT_USAGE stores long history.
USE ROLE ACCOUNTADMIN;

SELECT
  QUERY_ID,
  START_TIME,
  ROLE_NAME,
  WAREHOUSE_NAME,
  EXECUTION_STATUS,
  ERROR_CODE,
  ERROR_MESSAGE,
  QUERY_TAG
FROM SNOWFLAKE.ACCOUNT_USAGE.QUERY_HISTORY
WHERE START_TIME >= DATEADD(DAY, -7, CURRENT_TIMESTAMP())
  AND WAREHOUSE_NAME = 'INDUSTRIAL_SERVICE_WH'
  AND ERROR_CODE IS NOT NULL
ORDER BY START_TIME DESC;
