-- Non-destructive rollback drill using a session-scoped temporary table.
USE ROLE SYSADMIN;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA OPERATIONS;

CREATE OR REPLACE TEMPORARY TABLE TRANSACTION_ROLLBACK_DRILL (
  DRILL_ID VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP()
);

BEGIN;
INSERT INTO TRANSACTION_ROLLBACK_DRILL (DRILL_ID) VALUES ('ROLLBACK-CHECK');
ROLLBACK;

SELECT COUNT(*) AS ROWS_AFTER_ROLLBACK
FROM TRANSACTION_ROLLBACK_DRILL;

DROP TABLE IF EXISTS TRANSACTION_ROLLBACK_DRILL;
