-- Verify raw tables, source counts, and the latest ingestion audit records.
USE ROLE ISP_LOADER;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SHOW TABLES IN SCHEMA RAW;

SELECT 'ERP_CUSTOMERS' AS TABLE_NAME, COUNT(*) AS ROW_COUNT FROM RAW.ERP_CUSTOMERS
UNION ALL
SELECT 'ERP_SITES', COUNT(*) FROM RAW.ERP_SITES
UNION ALL
SELECT 'ERP_ASSETS', COUNT(*) FROM RAW.ERP_ASSETS
UNION ALL
SELECT 'CRM_SERVICE_CONTRACTS', COUNT(*) FROM RAW.CRM_SERVICE_CONTRACTS
UNION ALL
SELECT 'CRM_CUSTOMER_CASES', COUNT(*) FROM RAW.CRM_CUSTOMER_CASES
UNION ALL
SELECT 'CRM_CASE_STATUS_HISTORY', COUNT(*) FROM RAW.CRM_CASE_STATUS_HISTORY
UNION ALL
SELECT 'ERP_TECHNICIANS', COUNT(*) FROM RAW.ERP_TECHNICIANS
UNION ALL
SELECT 'ERP_SERVICE_ORDERS', COUNT(*) FROM RAW.ERP_SERVICE_ORDERS
UNION ALL
SELECT 'ERP_PARTS', COUNT(*) FROM RAW.ERP_PARTS
UNION ALL
SELECT 'ERP_SERVICE_ORDER_PARTS', COUNT(*) FROM RAW.ERP_SERVICE_ORDER_PARTS
UNION ALL
SELECT 'ERP_SERVICE_COSTS', COUNT(*) FROM RAW.ERP_SERVICE_COSTS
UNION ALL
SELECT 'MONITORING_EQUIPMENT_ALERTS', COUNT(*) FROM RAW.MONITORING_EQUIPMENT_ALERTS
UNION ALL
SELECT 'FIELD_SERVICE_TECHNICIAN_NOTES', COUNT(*)
FROM RAW.FIELD_SERVICE_TECHNICIAN_NOTES
ORDER BY TABLE_NAME;

SELECT
  RUN_ID,
  STARTED_AT,
  FINISHED_AT,
  STATUS,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  ERROR_MESSAGE
FROM OPERATIONS.PIPELINE_RUNS
ORDER BY STARTED_AT DESC
LIMIT 5;

SELECT
  RUN_ID,
  DATASET_NAME,
  SOURCE_FILE_NAME,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  ROWS_RECEIVED - ROWS_LOADED - ROWS_REJECTED AS ROWS_SKIPPED,
  STATUS
FROM OPERATIONS.INGESTION_RESULTS
WHERE RUN_ID = (
  SELECT RUN_ID
  FROM OPERATIONS.PIPELINE_RUNS
  ORDER BY STARTED_AT DESC
  LIMIT 1
)
ORDER BY DATASET_NAME;

SELECT COUNT(*) AS REJECTION_RECORD_COUNT
FROM OPERATIONS.REJECTED_RECORDS;
