-- Compare the two most recent completed runs after loading identical files twice.
USE ROLE ISP_LOADER;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;

WITH RECENT_RUNS AS (
  SELECT
    RUN_ID,
    STARTED_AT,
    STATUS,
    ROWS_RECEIVED,
    ROWS_LOADED,
    ROWS_REJECTED,
    ROW_NUMBER() OVER (ORDER BY STARTED_AT DESC) AS RECENCY
  FROM OPERATIONS.PIPELINE_RUNS
  WHERE STATUS LIKE 'COMPLETED%'
)
SELECT
  RECENCY,
  RUN_ID,
  STARTED_AT,
  STATUS,
  ROWS_RECEIVED,
  ROWS_LOADED,
  ROWS_REJECTED,
  ROWS_RECEIVED - ROWS_LOADED - ROWS_REJECTED AS ROWS_SKIPPED
FROM RECENT_RUNS
WHERE RECENCY <= 2
ORDER BY RECENCY;
