USE ROLE ISP_ANALYST;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA ANALYTICS;

SELECT
  COUNT_IF(NOT OUTPUT_VALID) AS INVALID_OUTPUT_ROWS,
  COUNT_IF(FAULT_CONFIDENCE < 0 OR FAULT_CONFIDENCE > 1) AS INVALID_FAULT_CONFIDENCE_ROWS,
  COUNT_IF(PRIORITY_CONFIDENCE < 0 OR PRIORITY_CONFIDENCE > 1)
    AS INVALID_PRIORITY_CONFIDENCE_ROWS,
  COUNT_IF(GENERATED_SUMMARY IS NULL OR TRIM(GENERATED_SUMMARY) = '')
    AS EMPTY_SUMMARY_ROWS
FROM MART_TECHNICIAN_NOTE_ENRICHMENT;

SELECT
  PREDICTED_FAULT_CATEGORY,
  COUNT(*) AS NOTE_COUNT,
  ROUND(AVG(FAULT_CONFIDENCE), 4) AS AVERAGE_CONFIDENCE
FROM MART_TECHNICIAN_NOTE_ENRICHMENT
GROUP BY PREDICTED_FAULT_CATEGORY
ORDER BY NOTE_COUNT DESC, PREDICTED_FAULT_CATEGORY;

SELECT
  PREDICTED_PRIORITY,
  COUNT(*) AS NOTE_COUNT,
  ROUND(AVG(PRIORITY_CONFIDENCE), 4) AS AVERAGE_CONFIDENCE
FROM MART_TECHNICIAN_NOTE_ENRICHMENT
GROUP BY PREDICTED_PRIORITY
ORDER BY NOTE_COUNT DESC, PREDICTED_PRIORITY;
