USE ROLE ISP_ANALYST;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA ANALYTICS;

SELECT
  NOTE_ID,
  NOTE_TYPE,
  PREDICTED_FAULT_CATEGORY,
  PREDICTED_PRIORITY,
  PREDICTED_COMPONENT,
  RECOMMENDED_TEAM,
  GENERATED_SUMMARY,
  FAULT_CONFIDENCE,
  PRIORITY_CONFIDENCE
FROM MART_TECHNICIAN_NOTE_ENRICHMENT
ORDER BY NOTE_ID
LIMIT 20;
