
USE ROLE ISP_TRANSFORMER;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SHOW VIEWS IN SCHEMA STAGING;
SHOW TABLES IN SCHEMA CORE;
SHOW TABLES IN SCHEMA ANALYTICS;

SELECT 'STG_ERP_CUSTOMERS' AS MODEL_NAME, COUNT(*) AS ROW_COUNT FROM STAGING.STG_ERP_CUSTOMERS
UNION ALL SELECT 'STG_ERP_SITES', COUNT(*) FROM STAGING.STG_ERP_SITES
UNION ALL SELECT 'STG_ERP_ASSETS', COUNT(*) FROM STAGING.STG_ERP_ASSETS
UNION ALL SELECT 'STG_CRM_SERVICE_CONTRACTS', COUNT(*) FROM STAGING.STG_CRM_SERVICE_CONTRACTS
UNION ALL SELECT 'STG_CRM_CUSTOMER_CASES', COUNT(*) FROM STAGING.STG_CRM_CUSTOMER_CASES
UNION ALL SELECT 'STG_CRM_CASE_STATUS_HISTORY', COUNT(*) FROM STAGING.STG_CRM_CASE_STATUS_HISTORY
UNION ALL SELECT 'STG_ERP_TECHNICIANS', COUNT(*) FROM STAGING.STG_ERP_TECHNICIANS
UNION ALL SELECT 'STG_ERP_SERVICE_ORDERS', COUNT(*) FROM STAGING.STG_ERP_SERVICE_ORDERS
UNION ALL SELECT 'STG_ERP_PARTS', COUNT(*) FROM STAGING.STG_ERP_PARTS
UNION ALL SELECT 'STG_ERP_SERVICE_ORDER_PARTS', COUNT(*) FROM STAGING.STG_ERP_SERVICE_ORDER_PARTS
UNION ALL SELECT 'STG_ERP_SERVICE_COSTS', COUNT(*) FROM STAGING.STG_ERP_SERVICE_COSTS
UNION ALL SELECT 'STG_MONITORING_EQUIPMENT_ALERTS', COUNT(*)
  FROM STAGING.STG_MONITORING_EQUIPMENT_ALERTS
UNION ALL SELECT 'STG_FIELD_SERVICE_TECHNICIAN_NOTES', COUNT(*)
  FROM STAGING.STG_FIELD_SERVICE_TECHNICIAN_NOTES
ORDER BY MODEL_NAME;
