
USE ROLE ISP_TRANSFORMER;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SELECT COUNT(*) AS NEGATIVE_SERVICE_COSTS
FROM CORE.FACT_SERVICE_COST
WHERE COST_AMOUNT_EUR < 0;

SELECT COUNT(*) AS INVALID_COMPLETED_ORDERS
FROM CORE.FACT_SERVICE_ORDER
WHERE ORDER_STATUS = 'COMPLETED'
  AND (ACTUAL_START_AT IS NULL OR COMPLETED_AT IS NULL OR COMPLETED_AT < ACTUAL_START_AT);

SELECT COUNT(*) AS INVALID_CASE_TIMESTAMPS
FROM CORE.FACT_SERVICE_CASE
WHERE RESPONSE_DUE_AT <= CREATED_AT
   OR RESOLUTION_DUE_AT <= CREATED_AT
   OR FIRST_RESPONSE_AT < CREATED_AT
   OR RESOLVED_AT < CREATED_AT
   OR CLOSED_AT < RESOLVED_AT;

SELECT COUNT(*) AS INVALID_PART_LINES
FROM CORE.FACT_SERVICE_ORDER_PART
WHERE QUANTITY <= 0 OR UNIT_COST_EUR < 0 OR DELIVERED_AT < REQUESTED_AT;
