
USE ROLE ISP_TRANSFORMER;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SELECT
  COUNT(*) AS SNAPSHOT_ROWS,
  COUNT_IF(DBT_VALID_TO IS NULL) AS CURRENT_ROWS,
  COUNT_IF(DBT_VALID_TO IS NOT NULL) AS HISTORICAL_ROWS
FROM CORE.SNAP_ASSET_HISTORY;

SELECT *
FROM ANALYTICS.MART_SERVICE_OPERATIONS
ORDER BY REPORTING_MONTH DESC, CASE_COUNT DESC
LIMIT 20;

SELECT *
FROM ANALYTICS.MART_ASSET_RELIABILITY
ORDER BY IS_HIGH_RISK DESC, DOWNTIME_HOURS DESC
LIMIT 20;

SELECT *
FROM ANALYTICS.MART_CUSTOMER_PERFORMANCE
ORDER BY SERVICE_COST_EUR DESC
LIMIT 20;
