USE ROLE ISP_TRANSFORMER;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;

SELECT
  COUNT(*) AS KPI_SUMMARY_ROWS,
  MIN(REPORTING_AS_OF) AS REPORTING_AS_OF
FROM ANALYTICS.MART_KPI_SUMMARY;

SELECT
  COUNT(*) AS FIRST_TIME_FIX_ELIGIBLE_CASES,
  COUNT_IF(FIRST_TIME_FIX_FLAG) AS FIRST_TIME_FIX_CASES
FROM CORE.INT_CASE_FIRST_TIME_FIX;

SELECT
  COUNT(*) AS REPEAT_FAILURE_ELIGIBLE_CASES,
  COUNT_IF(REPEAT_FAILURE_FLAG) AS REPEAT_FAILURE_CASES
FROM CORE.INT_CASE_REPEAT_FAILURE;

SELECT
  COUNT(*) AS ASSETS_WITH_DOWNTIME,
  SUM(DOWNTIME_HOURS) AS TOTAL_DOWNTIME_HOURS
FROM CORE.INT_ASSET_DOWNTIME;
