USE ROLE ISP_ANALYST;
USE WAREHOUSE INDUSTRIAL_SERVICE_WH;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA ANALYTICS;

SELECT COUNT(*) AS INVALID_RATE_ROWS
FROM MART_KPI_SUMMARY
WHERE RESPONSE_SLA_COMPLIANCE_RATE NOT BETWEEN 0 AND 1
   OR RESOLUTION_SLA_COMPLIANCE_RATE NOT BETWEEN 0 AND 1
   OR FIRST_TIME_FIX_RATE NOT BETWEEN 0 AND 1
   OR REPEAT_FAILURE_RATE NOT BETWEEN 0 AND 1
   OR ALERT_TO_CASE_CONVERSION_RATE NOT BETWEEN 0 AND 1;

SELECT COUNT(*) AS NEGATIVE_METRIC_ROWS
FROM MART_KPI_SUMMARY
WHERE OPEN_CASE_COUNT < 0
   OR CRITICAL_OPEN_CASE_COUNT < 0
   OR MEAN_RESOLUTION_HOURS < 0
   OR MEDIAN_RESOLUTION_HOURS < 0
   OR TOTAL_DOWNTIME_HOURS < 0
   OR AVERAGE_PART_DELIVERY_DELAY_HOURS < 0
   OR TOTAL_SERVICE_COST_EUR < 0;
