-- Add a monthly warehouse credit limit. Run with ACCOUNTADMIN.
USE ROLE ACCOUNTADMIN;

CREATE RESOURCE MONITOR IF NOT EXISTS INDUSTRIAL_SERVICE_MONITOR
  WITH CREDIT_QUOTA = 5
  FREQUENCY = MONTHLY
  START_TIMESTAMP = IMMEDIATELY
  TRIGGERS
    ON 75 PERCENT DO NOTIFY
    ON 90 PERCENT DO SUSPEND
    ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE INDUSTRIAL_SERVICE_WH
  SET RESOURCE_MONITOR = INDUSTRIAL_SERVICE_MONITOR;
