-- Grant least-privilege access to the functional roles.
USE ROLE SECURITYADMIN;

GRANT USAGE ON WAREHOUSE INDUSTRIAL_SERVICE_WH TO ROLE ISP_LOADER;
GRANT USAGE ON WAREHOUSE INDUSTRIAL_SERVICE_WH TO ROLE ISP_TRANSFORMER;
GRANT USAGE ON WAREHOUSE INDUSTRIAL_SERVICE_WH TO ROLE ISP_ANALYST;
GRANT USAGE, OPERATE, MONITOR ON WAREHOUSE INDUSTRIAL_SERVICE_WH TO ROLE ISP_ADMIN;

GRANT USAGE ON DATABASE INDUSTRIAL_SERVICE_DB TO ROLE ISP_LOADER;
GRANT USAGE ON DATABASE INDUSTRIAL_SERVICE_DB TO ROLE ISP_TRANSFORMER;
GRANT USAGE ON DATABASE INDUSTRIAL_SERVICE_DB TO ROLE ISP_ANALYST;

GRANT USAGE ON SCHEMA INDUSTRIAL_SERVICE_DB.RAW TO ROLE ISP_LOADER;
GRANT USAGE ON SCHEMA INDUSTRIAL_SERVICE_DB.OPERATIONS TO ROLE ISP_LOADER;
GRANT CREATE TABLE, CREATE STAGE, CREATE FILE FORMAT
  ON SCHEMA INDUSTRIAL_SERVICE_DB.RAW TO ROLE ISP_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.RAW TO ROLE ISP_LOADER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.RAW TO ROLE ISP_LOADER;
GRANT SELECT, INSERT, UPDATE
  ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.OPERATIONS TO ROLE ISP_LOADER;
GRANT SELECT, INSERT, UPDATE
  ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.OPERATIONS TO ROLE ISP_LOADER;

GRANT USAGE ON ALL SCHEMAS IN DATABASE INDUSTRIAL_SERVICE_DB TO ROLE ISP_TRANSFORMER;
GRANT USAGE ON FUTURE SCHEMAS IN DATABASE INDUSTRIAL_SERVICE_DB TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.RAW TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.RAW
  TO ROLE ISP_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA INDUSTRIAL_SERVICE_DB.STAGING TO ROLE ISP_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA INDUSTRIAL_SERVICE_DB.CORE TO ROLE ISP_TRANSFORMER;
GRANT CREATE TABLE, CREATE VIEW
  ON SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.STAGING TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.STAGING TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.CORE TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.CORE TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT, UPDATE, DELETE, TRUNCATE
  ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.STAGING TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.STAGING
  TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.CORE TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.CORE
  TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON ALL VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_TRANSFORMER;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.OPERATIONS
  TO ROLE ISP_TRANSFORMER;
GRANT SELECT, INSERT ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.OPERATIONS
  TO ROLE ISP_TRANSFORMER;

GRANT USAGE ON SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS TO ROLE ISP_ANALYST;
GRANT SELECT ON ALL TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_ANALYST;
GRANT SELECT ON FUTURE TABLES IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_ANALYST;
GRANT SELECT ON ALL VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_ANALYST;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA INDUSTRIAL_SERVICE_DB.ANALYTICS
  TO ROLE ISP_ANALYST;
