-- Create the audit tables used by ingestion and data-quality jobs.
USE ROLE SYSADMIN;
USE DATABASE INDUSTRIAL_SERVICE_DB;
USE SCHEMA OPERATIONS;

CREATE TABLE IF NOT EXISTS PIPELINE_RUNS (
  RUN_ID VARCHAR NOT NULL,
  SOURCE_NAME VARCHAR NOT NULL,
  STARTED_AT TIMESTAMP_TZ NOT NULL,
  FINISHED_AT TIMESTAMP_TZ,
  STATUS VARCHAR NOT NULL,
  ROWS_RECEIVED NUMBER(38, 0) NOT NULL DEFAULT 0,
  ROWS_LOADED NUMBER(38, 0) NOT NULL DEFAULT 0,
  ROWS_REJECTED NUMBER(38, 0) NOT NULL DEFAULT 0,
  ERROR_MESSAGE VARCHAR,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_PIPELINE_RUNS PRIMARY KEY (RUN_ID)
);

CREATE TABLE IF NOT EXISTS INGESTION_RESULTS (
  RESULT_ID VARCHAR NOT NULL,
  RUN_ID VARCHAR NOT NULL,
  DATASET_NAME VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  LOAD_BATCH_ID VARCHAR NOT NULL,
  ROWS_RECEIVED NUMBER(38, 0) NOT NULL DEFAULT 0,
  ROWS_LOADED NUMBER(38, 0) NOT NULL DEFAULT 0,
  ROWS_REJECTED NUMBER(38, 0) NOT NULL DEFAULT 0,
  STATUS VARCHAR NOT NULL,
  CREATED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_INGESTION_RESULTS PRIMARY KEY (RESULT_ID)
);

CREATE TABLE IF NOT EXISTS REJECTED_RECORDS (
  REJECTION_ID VARCHAR NOT NULL,
  RUN_ID VARCHAR NOT NULL,
  LOAD_BATCH_ID VARCHAR NOT NULL,
  SOURCE_SYSTEM VARCHAR NOT NULL,
  SOURCE_FILE_NAME VARCHAR NOT NULL,
  SOURCE_ROW_NUMBER NUMBER(38, 0),
  BUSINESS_IDENTIFIER VARCHAR,
  REJECTION_CODE VARCHAR NOT NULL,
  REJECTION_MESSAGE VARCHAR NOT NULL,
  RAW_RECORD_PAYLOAD VARIANT NOT NULL,
  REJECTED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_REJECTED_RECORDS PRIMARY KEY (REJECTION_ID)
);

CREATE TABLE IF NOT EXISTS DATA_QUALITY_RESULTS (
  RESULT_ID VARCHAR NOT NULL,
  RUN_ID VARCHAR,
  CHECK_NAME VARCHAR NOT NULL,
  DATASET_NAME VARCHAR,
  STATUS VARCHAR NOT NULL,
  FAILED_ROW_COUNT NUMBER(38, 0) NOT NULL DEFAULT 0,
  DETAILS VARIANT,
  CHECKED_AT TIMESTAMP_TZ NOT NULL DEFAULT CURRENT_TIMESTAMP(),
  CONSTRAINT PK_DATA_QUALITY_RESULTS PRIMARY KEY (RESULT_ID)
);
