-- Inspect the created objects and grants without changing data.
USE ROLE SYSADMIN;

SELECT CURRENT_ACCOUNT() AS ACCOUNT_NAME,
       CURRENT_USER() AS USER_NAME,
       CURRENT_ROLE() AS ACTIVE_ROLE;

SHOW WAREHOUSES LIKE 'INDUSTRIAL_SERVICE_WH';
SHOW DATABASES LIKE 'INDUSTRIAL_SERVICE_DB';
SHOW SCHEMAS IN DATABASE INDUSTRIAL_SERVICE_DB;
SHOW RESOURCE MONITORS LIKE 'INDUSTRIAL_SERVICE_MONITOR';
SHOW ROLES LIKE 'ISP_%';

SHOW GRANTS TO ROLE ISP_LOADER;
SHOW GRANTS TO ROLE ISP_TRANSFORMER;
SHOW GRANTS TO ROLE ISP_ANALYST;
SHOW FUTURE GRANTS TO ROLE ISP_LOADER;
SHOW FUTURE GRANTS TO ROLE ISP_TRANSFORMER;
SHOW FUTURE GRANTS TO ROLE ISP_ANALYST;

SELECT TABLE_SCHEMA,
       TABLE_NAME
FROM INDUSTRIAL_SERVICE_DB.INFORMATION_SCHEMA.TABLES
WHERE TABLE_SCHEMA = 'OPERATIONS'
ORDER BY TABLE_NAME;
